services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file: ".env"
    restart: always
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:17
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lrqm