version: '3.8'

services:
  postgres:
    image: postgres:17
    ports:
      - 5430:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lrqm